package com.netbiis.models;
// Generated 4 de nov. de 2022 11:28:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", uniqueConstraints = @UniqueConstraint(columnNames = "nome_categoria"))
public class Categoria implements java.io.Serializable {

	private Integer idCategoria;
	private String nomeCategoria;
	private Set<Produtos> produtoses = new HashSet<Produtos>(0);

	public Categoria() {
	}

	public Categoria(String nomeCategoria) {
		this.nomeCategoria = nomeCategoria;
	}

	public Categoria(String nomeCategoria, Set<Produtos> produtoses) {
		this.nomeCategoria = nomeCategoria;
		this.produtoses = produtoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_categoria", unique = true, nullable = false)
	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "nome_categoria", unique = true, nullable = false, length = 45)
	public String getNomeCategoria() {
		return this.nomeCategoria;
	}

	public void setNomeCategoria(String nomeCategoria) {
		this.nomeCategoria = nomeCategoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Produtos> getProdutoses() {
		return this.produtoses;
	}

	public void setProdutoses(Set<Produtos> produtoses) {
		this.produtoses = produtoses;
	}

}
