package com.netbiis.models;
// Generated 4 de nov. de 2022 22:07:32 by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", uniqueConstraints = { @UniqueConstraint(columnNames = "cliente_cpf"),
		@UniqueConstraint(columnNames = "cliente_name") })
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private String clienteName;
	private String clienteCpf;
	private String clienteEndereco;
	private String clienteNumero;
	private String clienteCartao;
	private Set<Pagamento> pagamentos = new HashSet<Pagamento>(0);

	public Cliente() {
	}

	public Cliente(String clienteName, String clienteCpf, String clienteEndereco, String clienteNumero,
			String clienteCartao) {
		this.clienteName = clienteName;
		this.clienteCpf = clienteCpf;
		this.clienteEndereco = clienteEndereco;
		this.clienteNumero = clienteNumero;
		this.clienteCartao = clienteCartao;
	}

	public Cliente(String clienteName, String clienteCpf, String clienteEndereco, String clienteNumero,
			String clienteCartao, Set<Pagamento> pagamentos) {
		this.clienteName = clienteName;
		this.clienteCpf = clienteCpf;
		this.clienteEndereco = clienteEndereco;
		this.clienteNumero = clienteNumero;
		this.clienteCartao = clienteCartao;
		this.pagamentos = pagamentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "cliente_name", unique = true, nullable = false, length = 45)
	public String getClienteName() {
		return this.clienteName;
	}

	public void setClienteName(String clienteName) {
		this.clienteName = clienteName;
	}

	@Column(name = "cliente_cpf", unique = true, nullable = false, length = 45)
	public String getClienteCpf() {
		return this.clienteCpf;
	}

	public void setClienteCpf(String clienteCpf) {
		this.clienteCpf = clienteCpf;
	}

	@Column(name = "cliente_endereco", nullable = false, length = 45)
	public String getClienteEndereco() {
		return this.clienteEndereco;
	}

	public void setClienteEndereco(String clienteEndereco) {
		this.clienteEndereco = clienteEndereco;
	}

	@Column(name = "cliente_numero", nullable = false, length = 45)
	public String getClienteNumero() {
		return this.clienteNumero;
	}

	public void setClienteNumero(String clienteNumero) {
		this.clienteNumero = clienteNumero;
	}

	@Column(name = "cliente_cartao", nullable = false, length = 45)
	public String getClienteCartao() {
		return this.clienteCartao;
	}

	public void setClienteCartao(String clienteCartao) {
		this.clienteCartao = clienteCartao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Pagamento> getPagamentos() {
		return this.pagamentos;
	}

	public void setPagamentos(Set<Pagamento> pagamentos) {
		this.pagamentos = pagamentos;
	}

}
