package com.netbiis.models;
// Generated 4 de nov. de 2022 11:28:17 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "pagamento")
public class Pagamento implements java.io.Serializable {

	private Integer idPagamento;
	private Cliente cliente;
	private Produtos produtos;

	public Pagamento() {
	}

	public Pagamento(Cliente cliente, Produtos produtos) {
		this.cliente = cliente;
		this.produtos = produtos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pagamento", unique = true, nullable = false)
	public Integer getIdPagamento() {
		return this.idPagamento;
	}

	public void setIdPagamento(Integer idPagamento) {
		this.idPagamento = idPagamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produto", nullable = false)
	public Produtos getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Produtos produtos) {
		this.produtos = produtos;
	}

}
